# Generated by Django 3.0.4 on 2020-04-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursoOnline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcao',
            name='certo',
            field=models.BooleanField(default=False),
        ),
    ]
