# Generated by Django 3.0.4 on 2020-05-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursoOnline', '0002_opcao_certo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='isLink',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='link',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='participante',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
