# Generated by Django 3.0.4 on 2020-05-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursoOnline', '0003_auto_20200504_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='linkname',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
