# Generated by Django 3.0.4 on 2020-05-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursoOnline', '0004_curso_linkname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='link',
            field=models.CharField(default='null', max_length=2000),
        ),
    ]
